### PR TITLE
Containerize zarr conversion

### PR DESCRIPTION
**Pull request by willirath**
This will lead to a streamlined Zarr conversion.

Please don't merge yet.

- [ ] Have only one script for Zarr conversion
- [ ] Adapt documentation to reflect project id and variable flags

### CODE REVIEW

**Review by eshchekinova — APPROVED** [review]
Revewed

**Review by eshchekinova — COMMENTED** [review]
Reviewed

**Comment by willirath** [comment]
@eshchekinova Can you have a look again. Tests are currently failing, but I'll tackle this once we have addressed #13.

**Review by eshchekinova — APPROVED** [review]
Approved

**Review by eshchekinova — APPROVED** [review]
Approved

**Pull request merged**
