### PR TITLE
[DO NOT MERGE YET] Review / Refactor

### PR DESCRIPTION
**Pull request by willirath**
This branch / PR will contain some changes and comments relative to the initial version.

### CODE REVIEW

**Comment by willirath** [comment]
40f130995ebb34337b58434f657a69b4bd3a0a6f transforms the README to markdown and does some light editing / rewording.

[This is the final rendered README as it will be displayed by Github](https://github.com/eshchekinova/example-cmems-download-automation/blob/40f130995ebb34337b58434f657a69b4bd3a0a6f/README.md)

[Here's a good intro to (Github's) markdown.](https://docs.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax)

**Comment by willirath** [comment]
4f22ce533fe30f61aa4560b4e7e09f8d46d9cb96 slightly modifies the shell scripts used for downloading so that they follow best practices for coding shell scripts (I've used https://www.shellcheck.net/ for this.) It also adds environment variables for the username and password and makes sure these are explained in the README.

**Comment by willirath** [comment]
bf0387a6895b08a99dc78af1f216fe0486a9446f ensures we don't accidentally track netCDF of CSV files.

**Comment by willirath** [comment]
03ae8e83a830b7b4d1a85795a92c564dac938723 uses [`pathlib.Path`](https://docs.python.org/3/library/pathlib.html) for handling directories and files, and switches to Xarray for [opening / loading the netCDF files](http://xarray.pydata.org/en/stable/quick-overview.html?highlight=open_dataset#read-write-netcdf-files), and for [conversion to a tabular dataframe](http://xarray.pydata.org/en/stable/quick-overview.html?highlight=to_dataframe#pandas), and to Pandas for [writing the CSV files](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html).

**Comment by willirath** [comment]
Next step is to make sure the download and the conversion run in containers. We could either build one container that can do both, but this will turn out more complicated if we want to add more conversions or intermediate steps as we'd have to make sure we have one container that is compatible with all requirements from all steps. So I'd go for splitting into two containers.

**Comment by willirath** [comment]
e460edcbb8539cc9695699a999af0972eb2ccdeb switches to Docker for execution of the download and the conversion step:

- There's two environments defined in two Docker files: `Dockerfile_MotuCl` for the download and `Dockerfile_NetCDF2CSV` for the NC2CSV conversion
- The README shows how to [build](https://docs.docker.com/engine/reference/commandline/build/) the container images from the Docker files and how to [run](https://docs.docker.com/engine/reference/commandline/run/) the steps within containers.

**Comment by willirath** [comment]
The next step could be making the paths and time steps explicit arguments to the download and conversion step, so we can make it easier to re-use the tools with different paths or for different time steps.

**Comment by willirath** [comment]
08e70a6cc7d169299e05f356170d79e17745718e uses [positional parameters](https://linuxcommand.org/lc3_wss0120.php) for the Bash scripts and [the stdlib module `argparse`](https://docs.python.org/3/library/argparse.html) for the Python scripts and adds the possibility of choosing the path for the data downloads and conversions.

**Review by eshchekinova — APPROVED** [review]
Merging changes : Docker files, gitignore, explicit directory as an argument , adding xarray, python library, netcdf -> xarray->panda->csv conversion

**Pull request merged**
